// <auto-generated />
namespace SleepMakeSense.Migrations.SleepbetaDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test21));
        
        string IMigrationMetadata.Id
        {
            get { return "201803300921138_test21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
