// <auto-generated />
namespace SleepMakeSense.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class test4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test4));
        
        string IMigrationMetadata.Id
        {
            get { return "201507140844278_test4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
